fos_user:
    db_driver: orm
    user_class: App\Entity\User
    firewall_name: main
    from_email:
        address: foo
        sender_name: bar

    resetting:
        email:
            from_email:
                address:        resetting@example.com
                sender_name:    Demo Resetting